twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/.components': component
        '%kernel.project_dir%/templates/.forms': form
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@form/bank/account/charge-groups-form.html.twig'
        - '@form/bank/account/charge-form.html.twig'

when@test:
    twig:
        strict_variables: true
