version: '3.0'
services:
    database:
        labels:
            - traefik.enable=false

    web:
        labels:
            - traefik.enable=true
            - traefik.http.routers.moneyer_https.tls=true
            - traefik.http.routers.moneyer_https.rule=Host(`moneyer.local`)
            - traefik.http.routers.moneyer_https.entryPoints=websecure
            - traefik.http.routers.moneyer_http.rule=Host(`moneyer.local`)
            - traefik.http.routers.moneyer_http.entryPoints=web

    phpmyadmin:
        labels:
            - traefik.enable=true
            - traefik.http.routers.moneyer_phpmyadmin.rule=Host(`phpmyadmin.moneyer.local`)
            - traefik.http.routers.moneyer_phpmyadmin.entryPoints=web

    smtp:
        labels:
            - traefik.enable=true
            - traefik.http.routers.moneyer_maildev.rule=Host(`maildev.moneyer.local`)
            - traefik.http.routers.moneyer_maildev.entryPoints=web
            - traefik.http.services.moneyer_maildev.loadbalancer.server.port=80
    traefik:
        image: traefik:v2.8
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - ${DOCKER_SOCK}:/var/run/docker.sock:ro
            - ./dockerfiles/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
            - ./dockerfiles/traefik/certs:/etc/certs/:ro
            - ./dockerfiles/traefik/confs:/etc/traefik/confs/:ro

    node:
        command: npm run watch
