version: "3.9"
services:
    database:
        labels:
            - traefik.enable=false
        networks:
            - default

    web:
        labels:
            - traefik.enable=true
            - traefik.http.routers.moneyer_https.tls=true
            - traefik.http.routers.moneyer_https.tls.certresolver=letsEncrypt
            - traefik.http.routers.moneyer_https.rule=Host(`moneyer.gwennael-jean.ovh`)
            - traefik.http.routers.moneyer_https.entryPoints=websecure
            - traefik.http.routers.moneyer_http.rule=Host(`moneyer.gwennael-jean.ovh`)
            - traefik.http.routers.moneyer_http.entryPoints=web
            - traefik.docker.network=proxy
        networks:
            - default
            - proxy

    phpmyadmin:
        labels:
            - traefik.enable=true
            - traefik.http.routers.moneyer_phpmyadmin.rule=Host(`phpmyadmin.moneyer.gwennael-jean.ovh`)
            - traefik.http.routers.moneyer_phpmyadmin.entryPoints=web
            - traefik.docker.network=proxy
        networks:
            - default
            - proxy

    smtp:
        labels:
            - traefik.enable=true
            - traefik.http.routers.moneyer_maildev.rule=Host(`maildev.moneyer.gwennael-jean.ovh`)
            - traefik.http.routers.moneyer_maildev.entryPoints=web
            - traefik.http.services.moneyer_maildev.loadbalancer.server.port=80
            - traefik.docker.network=proxy
        networks:
            - default
            - proxy

networks:
    proxy:
        external:
            name: proxy
